// Generated by CoffeeScript 1.6.2
var ViewManager;

ViewManager = (function() {
  function ViewManager() {}

  ViewManager.prototype.setView = function(viewName) {
    $("#contentwrapper").empty();
    this.currentViewName = viewName;
    return $.get("views/" + viewName + "/template.html", function(data) {
      console.log(data);
      return $("#contentwrapper").html(data);
    }, 'text');
  };

  return ViewManager;

})();
