// Generated by CoffeeScript 1.6.2
window.stopTheGame = function() {
  return 0;
};

window.setPlayerNames = function(text) {
  var ele, li, line, list, _i, _len;

  list = text.split("|");
  ele = document.getElementById("players");
  ele.innerHTML = "";
  for (_i = 0, _len = list.length; _i < _len; _i++) {
    line = list[_i];
    li = document.createElement("li");
    li.innerHTML = line;
    ele.appendChild(li);
  }
  return null;
};

window.populateSessionPages = function(sessionInfo) {
  return null;
};
